version: '3'
services:
  pm2:
    build:
      context: ./parrotm2
      dockerfile: ./parrotm2/Dockerfile
    image: pm2
    container_name: pm2
    ports:
      - "9090:9090"
      - "8082:8081"
    networks:
      - dft
  chatty:
    build:
      context: ./chatty
      dockerfile: ./chatty/Dockerfile
    image: chatty
    container_name: chatty
    ports:
      - "643:643"
    networks:
      - dft
  envoy:
    build:
      context: ./parrotm2
      dockerfile: ./parrotm2/envoy/Dockerfile
    image: pm2/envoy
    container_name: pm2_envoy
    ports:
      - "6969:8080"
    networks:
      - dft
networks:
  dft:
    driver: bridge