version: '3'
services:
  pm2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pm2
    container_name: pm2
    ports:
      - "9090:9090"
      - "8082:8081"
    networks:
      - dft
  envoy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    image: pm2/envoy
    container_name: pm2_envoy
    ports:
      - "6969:8080"
    networks:
      - dft
    volumes:
      - /etc/letsencrypt/live/tilid.com.br-0001:/etc/cert:ro
networks:
  dft:
    driver: bridge