package domain

const (
	ADDRESS_INVALID        = "ADDRESS_INVALID"
	CONTACT_INVALID        = "CONTACT_INVALID"
	TENANT_INVALID         = "TENANT_INVALID"
	TENANT_USER_INVALID    = "TENANT_USER_INVALID"
	TENANT_NOT_FOUND       = "TENANT_NOT_FOUND"
	TENANT_USER_NOT_FOUND  = "TENANT_USER_NOT_FOUND"
	CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
)
